apiVersion: apps/v1
kind: Deployment
metadata:
  name: walas-deployment
  labels:
    app: walas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walas
  template:
    metadata:
      labels:
        app: walas
    spec:
      containers:
      - name: walas
        image: gcr.io/walas-370711/walas-backend:latest
        ports:
        - containerPort: 8080