apiVersion: v1
kind: Pod
metadata:
  name: walas-pod
  labels:
    app: walas
spec:
  containers:
  - name: walas
    image: gcr.io/walas-370711/walas-backend:latest
    ports:
    - containerPort: 8080